apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  selector:
    app: my-nginx
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30500

---

apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  containers:
    - name: my-nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "200m"
          memory: "128Mi"